Implement a query based producer
allora-network/allora-producer pull request #5
Opened 2024-11-25 15:31 UTC by fernandofcampos

2024-11-25 19:31 UTC, spooktheducks requested changes

2024-11-25 19:31 UTC, spooktheducks commented on app/domain/service.go
> +	GetLatestNetworkInferences(ctx context.Context, topicID uint64) (*json.RawMessage, error)
`json.RawMessage` is already a `[]byte` so it's not really necessary to have a pointer to it

2024-11-25 19:31 UTC, spooktheducks commented on app/usecase/queryproducer.go
> +		time.Sleep(q.epochInterval)
Does this backfill if it misses an epoch for any reason?

2024-11-25 19:31 UTC, spooktheducks commented on app/usecase/queryproducer.go
> +func (q *QueryProducer) Execute(ctx context.Context) error {
For simplicity's sake, I would probably just merge this function into `QueryProcessor`

2024-11-25 19:31 UTC, spooktheducks commented on cmd/producer/main.go
>  	cleanup := func() {
If one of the previous statements returns an error, won't we be leaking DB connections?

2024-11-25 19:55 UTC, fernandofcampos commented on cmd/producer/main.go
>  	cleanup := func() {
None of those Close() methods return error.

2024-11-25 19:56 UTC, fernandofcampos commented on app/domain/service.go
> +	GetLatestNetworkInferences(ctx context.Context, topicID uint64) (*json.RawMessage, error)
Done

2024-11-25 19:57 UTC, fernandofcampos commented on app/usecase/queryproducer.go
> +		time.Sleep(q.epochInterval)
Not sure. In theory epoch interval is much larger than the execution time of each iteration.

2024-11-25 19:58 UTC, fernandofcampos commented on app/usecase/queryproducer.go
> +func (q *QueryProducer) Execute(ctx context.Context) error {
I wanted to separate coordination from processing, so we can sophisticate this in the future.

2024-11-26 14:04 UTC, KjetilVaa commented on app/service/query.go
> +}
I thought this guy was included in the GetLatestNetworkInferences response?

2024-11-26 14:29 UTC, fernandofcampos commented on app/service/queryprocessor.go
> +	metadata := json.RawMessage(fmt.Sprintf(`{"topic_id": %d}`, topicID))
See if it's possible to include block height at all metadata fields.

2024-11-26 14:53 UTC, fernandofcampos commented on app/service/query.go
> +}
It is but we decided to keep both.

2024-11-26 14:59 UTC, KjetilVaa submitted a review, later dismissed
Thanks @fernandofcampos for walking me through the this.
I think this looks good as a general framework for fetching data from API's in CRON-like manner. Some minor things we talked about:
- add block_height to the metadata field
- we need to keep in mind the versioning of the RPC endpoints. We could potentially switch to the RPC client however we would still need to update the imports for each new release.
Let's deploy this to unblock research after adding the block height

2024-11-26 20:51 UTC, fernandofcampos commented on app/service/queryprocessor.go
> +	metadata := json.RawMessage(fmt.Sprintf(`{"topic_id": %d}`, topicID))
Done

2024-11-27 11:46 UTC, KjetilVaa approved these changes
LGTM

2024-11-27 14:58 UTC, fernandofcampos commented on cmd/producer/main.go
>  	cleanup := func() {
Ah, now I get it. Good catch. I've handled that case.

2024-11-27 16:38 UTC, spooktheducks approved these changes

2024-11-27 16:44 UTC, merged