PROTO-2959: add ground truth for topics
allora-network/allora-producer pull request #7
Opened 2024-12-03 16:18 UTC by KjetilVaa

# Add Ground Truth Data Collection for Price and Volatility Topics
Adds functionality to fetch and process OHLC (Open, High, Low, Close) data from Upshot API for price and volatility topics.

## Key Changes
- Add OHLC data fetching and processing
- Configure topic-to-metric mapping in yaml config
- Calculate realized volatility using configured time windows
- Store ground truth data for each topic in existing query_results table (following the same CRON pattern)

2024-12-05 22:30 UTC, kpeluso commented on util/math.go
> +	// Calculate standard deviation
This is definitely what @clementupshot is using in the reputers, yeah?

2024-12-05 22:59 UTC, kpeluso commented on config/config.allora-localnet-1.yaml
> +allora_api:
In the BE I've been putting configs like this ("borderline env vars") in pg db so that we could edit them quickly if need be, without new deployments. Something to consider. Either way works though.

2024-12-05 22:59 UTC, kpeluso approved these changes

2024-12-09 14:00 UTC, KjetilVaa commented on util/math.go
> +	// Calculate standard deviation
Aligned with @clementupshot in the ticket discussion here yeah: https://linear.app/alloralabs/issue/PROTO-2959/add-ground-truth-time-series-for-price-prediction-and-volatility

2024-12-09 14:33 UTC, KjetilVaa commented on util/math.go
> +	// Calculate standard deviation
Ok, went through the reputer code for doing this with @clementupshot. Found a difference, the pandas std() function uses N - 1 (the sample standard deviation) while we used N (population standard deviation). Other than this, the math should match now. Thanks!

2024-12-09 14:36 UTC, fernandofcampos commented on config/config.allora-localnet-1.yaml
> +allora_api:
Every config in this file can be defined as an env variable that will have priority over whatever is defined in the config file itself, e.g. this one would become `allora_query_result_repository_url`.

2024-12-09 20:18 UTC, fernandofcampos requested changes

2024-12-09 20:18 UTC, fernandofcampos commented on app/service/query.go
> +		body, _ := io.ReadAll(resp.Body)
Why are you reading the body if the get failed?

2024-12-09 20:18 UTC, fernandofcampos commented on app/service/query.go
> +	return &ohlcResp, nil
you could return the data instead, because that's what you need right?

2024-12-10 08:49 UTC, KjetilVaa commented on app/usecase/queryproducer.go
> +	if processor.Config().APIKey != "" {
I was more thinking that it shouldn't be required to get an API key from us if they want to run our open-source producer. But sure, we can make it required.

2024-12-10 14:53 UTC, fernandofcampos approved these changes

2024-12-10 15:01 UTC, merged